defmodule Unicode.Transform.LatinAscii do
  @moduledoc """
  Compiled Latin-ASCII transform for fast codepoint-level transliteration.

  Auto-generated from `priv/transforms/Latin-ASCII.xml`.
  Regenerate with: `mix unicode.generate_latin_ascii`

  This module replaces the cursor-based rule engine with direct
  pattern-matched function heads, achieving O(1) lookup per codepoint
  via the BEAM's pattern matching dispatch.

  """

  @doc """
  Transforms a Latin string to ASCII.

  Applies NFD normalization, maps each codepoint to its ASCII equivalent,
  strips combining marks, and applies NFC normalization.

  ### Arguments

  * `string` — the input string.

  ### Returns

  The ASCII-transliterated string.

  """
  @spec transform(String.t()) :: String.t()
  def transform(string) do
    string
    |> String.normalize(:nfd)
    |> do_transform(<<>>)
    |> String.normalize(:nfc)
  end

  # Generated mapping rules (longest patterns first)
  defp do_transform(<<"🄐", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(A)">>)
  defp do_transform(<<"🄑", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(B)">>)
  defp do_transform(<<"🄒", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(C)">>)
  defp do_transform(<<"🄓", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(D)">>)
  defp do_transform(<<"🄔", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(E)">>)
  defp do_transform(<<"🄕", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(F)">>)
  defp do_transform(<<"🄖", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(G)">>)
  defp do_transform(<<"🄗", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(H)">>)
  defp do_transform(<<"🄘", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(I)">>)
  defp do_transform(<<"🄙", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(J)">>)
  defp do_transform(<<"🄚", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(K)">>)
  defp do_transform(<<"🄛", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(L)">>)
  defp do_transform(<<"🄜", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(M)">>)
  defp do_transform(<<"🄝", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(N)">>)
  defp do_transform(<<"🄞", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(O)">>)
  defp do_transform(<<"🄟", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(P)">>)
  defp do_transform(<<"🄠", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(Q)">>)
  defp do_transform(<<"🄡", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(R)">>)
  defp do_transform(<<"🄢", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(S)">>)
  defp do_transform(<<"🄣", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(T)">>)
  defp do_transform(<<"🄤", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(U)">>)
  defp do_transform(<<"🄥", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(V)">>)
  defp do_transform(<<"🄦", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(W)">>)
  defp do_transform(<<"🄧", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(X)">>)
  defp do_transform(<<"🄨", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(Y)">>)
  defp do_transform(<<"🄩", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(Z)">>)
  defp do_transform(<<"🄀", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "0.">>)
  defp do_transform(<<"🄁", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "0,">>)
  defp do_transform(<<"🄂", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "1,">>)
  defp do_transform(<<"🄃", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "2,">>)
  defp do_transform(<<"🄄", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "3,">>)
  defp do_transform(<<"🄅", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "4,">>)
  defp do_transform(<<"🄆", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "5,">>)
  defp do_transform(<<"🄇", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "6,">>)
  defp do_transform(<<"🄈", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "7,">>)
  defp do_transform(<<"🄉", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "8,">>)
  defp do_transform(<<"🄊", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "9,">>)
  defp do_transform(<<"ᴀ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "A">>)
  defp do_transform(<<"ᴁ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "AE">>)
  defp do_transform(<<"ᴃ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "B">>)
  defp do_transform(<<"ᴄ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "C">>)
  defp do_transform(<<"ᴅ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "D">>)
  defp do_transform(<<"ᴆ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "D">>)
  defp do_transform(<<"ᴇ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "E">>)
  defp do_transform(<<"ᴊ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "J">>)
  defp do_transform(<<"ᴋ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "K">>)
  defp do_transform(<<"ᴌ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "L">>)
  defp do_transform(<<"ᴍ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "M">>)
  defp do_transform(<<"ᴏ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "O">>)
  defp do_transform(<<"ᴘ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "P">>)
  defp do_transform(<<"ᴛ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "T">>)
  defp do_transform(<<"ᴜ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "U">>)
  defp do_transform(<<"ᴠ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "V">>)
  defp do_transform(<<"ᴡ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "W">>)
  defp do_transform(<<"ᴢ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Z">>)
  defp do_transform(<<"ᵫ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ue">>)
  defp do_transform(<<"ᵬ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "b">>)
  defp do_transform(<<"ᵭ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "d">>)
  defp do_transform(<<"ᵮ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "f">>)
  defp do_transform(<<"ᵯ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "m">>)
  defp do_transform(<<"ᵰ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "n">>)
  defp do_transform(<<"ᵱ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "p">>)
  defp do_transform(<<"ᵲ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "r">>)
  defp do_transform(<<"ᵳ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "r">>)
  defp do_transform(<<"ᵴ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "s">>)
  defp do_transform(<<"ᵵ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "t">>)
  defp do_transform(<<"ᵶ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "z">>)
  defp do_transform(<<"ᵺ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "th">>)
  defp do_transform(<<"ᵻ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "I">>)
  defp do_transform(<<"ᵽ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "p">>)
  defp do_transform(<<"ᵾ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "U">>)
  defp do_transform(<<"ᶀ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "b">>)
  defp do_transform(<<"ᶁ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "d">>)
  defp do_transform(<<"ᶂ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "f">>)
  defp do_transform(<<"ᶃ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "g">>)
  defp do_transform(<<"ᶄ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "k">>)
  defp do_transform(<<"ᶅ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "l">>)
  defp do_transform(<<"ᶆ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "m">>)
  defp do_transform(<<"ᶇ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "n">>)
  defp do_transform(<<"ᶈ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "p">>)
  defp do_transform(<<"ᶉ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "r">>)
  defp do_transform(<<"ᶊ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "s">>)
  defp do_transform(<<"ᶌ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "v">>)
  defp do_transform(<<"ᶍ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "x">>)
  defp do_transform(<<"ᶎ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "z">>)
  defp do_transform(<<"ᶏ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "a">>)
  defp do_transform(<<"ᶑ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "d">>)
  defp do_transform(<<"ᶒ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "e">>)
  defp do_transform(<<"ᶓ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "e">>)
  defp do_transform(<<"ᶖ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "i">>)
  defp do_transform(<<"ᶙ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "u">>)
  defp do_transform(<<"ẚ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "a">>)
  defp do_transform(<<"ẜ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "s">>)
  defp do_transform(<<"ẝ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "s">>)
  defp do_transform(<<"ẞ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "SS">>)
  defp do_transform(<<"Ỻ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "LL">>)
  defp do_transform(<<"ỻ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ll">>)
  defp do_transform(<<"Ỽ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "V">>)
  defp do_transform(<<"ỽ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "v">>)
  defp do_transform(<<"Ỿ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Y">>)
  defp do_transform(<<"ỿ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "y">>)
  defp do_transform(<<"Ⱡ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "L">>)
  defp do_transform(<<"ⱡ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "l">>)
  defp do_transform(<<"Ɫ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "L">>)
  defp do_transform(<<"Ᵽ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "P">>)
  defp do_transform(<<"Ɽ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "R">>)
  defp do_transform(<<"ⱥ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "a">>)
  defp do_transform(<<"ⱦ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "t">>)
  defp do_transform(<<"Ⱨ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "H">>)
  defp do_transform(<<"ⱨ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "h">>)
  defp do_transform(<<"Ⱪ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "K">>)
  defp do_transform(<<"ⱪ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "k">>)
  defp do_transform(<<"Ⱬ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Z">>)
  defp do_transform(<<"ⱬ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "z">>)
  defp do_transform(<<"Ɱ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "M">>)
  defp do_transform(<<"ⱱ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "v">>)
  defp do_transform(<<"Ⱳ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "W">>)
  defp do_transform(<<"ⱳ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "w">>)
  defp do_transform(<<"ⱴ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "v">>)
  defp do_transform(<<"ⱸ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "e">>)
  defp do_transform(<<"ⱺ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "o">>)
  defp do_transform(<<"Ȿ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "S">>)
  defp do_transform(<<"Ɀ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Z">>)
  defp do_transform(<<"ꜰ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "F">>)
  defp do_transform(<<"ꜱ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "S">>)
  defp do_transform(<<"Ꜳ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "AA">>)
  defp do_transform(<<"ꜳ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "aa">>)
  defp do_transform(<<"Ꜵ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "AO">>)
  defp do_transform(<<"ꜵ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ao">>)
  defp do_transform(<<"Ꜷ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "AU">>)
  defp do_transform(<<"ꜷ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "au">>)
  defp do_transform(<<"Ꜹ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "AV">>)
  defp do_transform(<<"ꜹ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "av">>)
  defp do_transform(<<"Ꜻ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "AV">>)
  defp do_transform(<<"ꜻ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "av">>)
  defp do_transform(<<"Ꜽ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "AY">>)
  defp do_transform(<<"ꜽ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ay">>)
  defp do_transform(<<"Ꝁ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "K">>)
  defp do_transform(<<"ꝁ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "k">>)
  defp do_transform(<<"Ꝃ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "K">>)
  defp do_transform(<<"ꝃ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "k">>)
  defp do_transform(<<"Ꝅ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "K">>)
  defp do_transform(<<"ꝅ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "k">>)
  defp do_transform(<<"Ꝇ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "L">>)
  defp do_transform(<<"ꝇ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "l">>)
  defp do_transform(<<"Ꝉ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "L">>)
  defp do_transform(<<"ꝉ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "l">>)
  defp do_transform(<<"Ꝋ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "O">>)
  defp do_transform(<<"ꝋ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "o">>)
  defp do_transform(<<"Ꝍ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "O">>)
  defp do_transform(<<"ꝍ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "o">>)
  defp do_transform(<<"Ꝏ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "OO">>)
  defp do_transform(<<"ꝏ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "oo">>)
  defp do_transform(<<"Ꝑ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "P">>)
  defp do_transform(<<"ꝑ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "p">>)
  defp do_transform(<<"Ꝓ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "P">>)
  defp do_transform(<<"ꝓ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "p">>)
  defp do_transform(<<"Ꝕ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "P">>)
  defp do_transform(<<"ꝕ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "p">>)
  defp do_transform(<<"Ꝗ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Q">>)
  defp do_transform(<<"ꝗ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "q">>)
  defp do_transform(<<"Ꝙ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Q">>)
  defp do_transform(<<"ꝙ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "q">>)
  defp do_transform(<<"Ꝟ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "V">>)
  defp do_transform(<<"ꝟ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "v">>)
  defp do_transform(<<"Ꝡ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "VY">>)
  defp do_transform(<<"ꝡ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "vy">>)
  defp do_transform(<<"Ꝥ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "TH">>)
  defp do_transform(<<"ꝥ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "th">>)
  defp do_transform(<<"Ꝧ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "TH">>)
  defp do_transform(<<"ꝧ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "th">>)
  defp do_transform(<<"ꝱ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "d">>)
  defp do_transform(<<"ꝲ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "l">>)
  defp do_transform(<<"ꝳ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "m">>)
  defp do_transform(<<"ꝴ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "n">>)
  defp do_transform(<<"ꝵ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "r">>)
  defp do_transform(<<"ꝶ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "R">>)
  defp do_transform(<<"ꝷ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "t">>)
  defp do_transform(<<"Ꝺ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "D">>)
  defp do_transform(<<"ꝺ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "d">>)
  defp do_transform(<<"Ꝼ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "F">>)
  defp do_transform(<<"ꝼ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "f">>)
  defp do_transform(<<"Ꞇ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "T">>)
  defp do_transform(<<"ꞇ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "t">>)
  defp do_transform(<<"Ꞑ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "N">>)
  defp do_transform(<<"ꞑ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "n">>)
  defp do_transform(<<"Ꞓ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "C">>)
  defp do_transform(<<"ꞓ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "c">>)
  defp do_transform(<<"Ꞡ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "G">>)
  defp do_transform(<<"ꞡ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "g">>)
  defp do_transform(<<"Ꞣ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "K">>)
  defp do_transform(<<"ꞣ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "k">>)
  defp do_transform(<<"Ꞥ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "N">>)
  defp do_transform(<<"ꞥ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "n">>)
  defp do_transform(<<"Ꞧ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "R">>)
  defp do_transform(<<"ꞧ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "r">>)
  defp do_transform(<<"Ꞩ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "S">>)
  defp do_transform(<<"ꞩ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "s">>)
  defp do_transform(<<"Ɦ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "H">>)
  defp do_transform(<<"ﬀ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ff">>)
  defp do_transform(<<"ﬁ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "fi">>)
  defp do_transform(<<"ﬂ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "fl">>)
  defp do_transform(<<"ﬃ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ffi">>)
  defp do_transform(<<"ﬄ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ffl">>)
  defp do_transform(<<"ﬅ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "st">>)
  defp do_transform(<<"ﬆ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "st">>)
  defp do_transform(<<"Ａ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "A">>)
  defp do_transform(<<"Ｂ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "B">>)
  defp do_transform(<<"Ｃ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "C">>)
  defp do_transform(<<"Ｄ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "D">>)
  defp do_transform(<<"Ｅ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "E">>)
  defp do_transform(<<"Ｆ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "F">>)
  defp do_transform(<<"Ｇ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "G">>)
  defp do_transform(<<"Ｈ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "H">>)
  defp do_transform(<<"Ｉ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "I">>)
  defp do_transform(<<"Ｊ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "J">>)
  defp do_transform(<<"Ｋ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "K">>)
  defp do_transform(<<"Ｌ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "L">>)
  defp do_transform(<<"Ｍ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "M">>)
  defp do_transform(<<"Ｎ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "N">>)
  defp do_transform(<<"Ｏ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "O">>)
  defp do_transform(<<"Ｐ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "P">>)
  defp do_transform(<<"Ｑ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Q">>)
  defp do_transform(<<"Ｒ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "R">>)
  defp do_transform(<<"Ｓ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "S">>)
  defp do_transform(<<"Ｔ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "T">>)
  defp do_transform(<<"Ｕ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "U">>)
  defp do_transform(<<"Ｖ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "V">>)
  defp do_transform(<<"Ｗ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "W">>)
  defp do_transform(<<"Ｘ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "X">>)
  defp do_transform(<<"Ｙ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Y">>)
  defp do_transform(<<"Ｚ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Z">>)
  defp do_transform(<<"ａ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "a">>)
  defp do_transform(<<"ｂ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "b">>)
  defp do_transform(<<"ｃ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "c">>)
  defp do_transform(<<"ｄ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "d">>)
  defp do_transform(<<"ｅ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "e">>)
  defp do_transform(<<"ｆ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "f">>)
  defp do_transform(<<"ｇ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "g">>)
  defp do_transform(<<"ｈ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "h">>)
  defp do_transform(<<"ｉ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "i">>)
  defp do_transform(<<"ｊ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "j">>)
  defp do_transform(<<"ｋ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "k">>)
  defp do_transform(<<"ｌ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "l">>)
  defp do_transform(<<"ｍ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "m">>)
  defp do_transform(<<"ｎ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "n">>)
  defp do_transform(<<"ｏ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "o">>)
  defp do_transform(<<"ｐ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "p">>)
  defp do_transform(<<"ｑ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "q">>)
  defp do_transform(<<"ｒ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "r">>)
  defp do_transform(<<"ｓ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "s">>)
  defp do_transform(<<"ｔ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "t">>)
  defp do_transform(<<"ｕ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "u">>)
  defp do_transform(<<"ｖ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "v">>)
  defp do_transform(<<"ｗ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "w">>)
  defp do_transform(<<"ｘ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "x">>)
  defp do_transform(<<"ｙ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "y">>)
  defp do_transform(<<"ｚ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "z">>)
  defp do_transform(<<"₠", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "CE">>)
  defp do_transform(<<"₢", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Cr">>)
  defp do_transform(<<"₣", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Fr.">>)
  defp do_transform(<<"₤", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "L.">>)
  defp do_transform(<<"₧", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Pts">>)
  defp do_transform(<<"₹", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Rs">>)
  defp do_transform(<<"₺", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "TL">>)
  defp do_transform(<<"℀", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "a/c">>)
  defp do_transform(<<"℁", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "a/s">>)
  defp do_transform(<<"ℂ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "C">>)
  defp do_transform(<<"℅", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "c/o">>)
  defp do_transform(<<"℆", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "c/u">>)
  defp do_transform(<<"ℊ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "g">>)
  defp do_transform(<<"ℋ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "H">>)
  defp do_transform(<<"ℌ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "x">>)
  defp do_transform(<<"ℍ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "H">>)
  defp do_transform(<<"ℎ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "h">>)
  defp do_transform(<<"ℐ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "I">>)
  defp do_transform(<<"ℑ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "I">>)
  defp do_transform(<<"ℒ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "L">>)
  defp do_transform(<<"ℓ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "l">>)
  defp do_transform(<<"ℕ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "N">>)
  defp do_transform(<<"№", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "No">>)
  defp do_transform(<<"℗", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(P)">>)
  defp do_transform(<<"℘", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "P">>)
  defp do_transform(<<"ℙ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "P">>)
  defp do_transform(<<"ℚ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Q">>)
  defp do_transform(<<"ℛ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "R">>)
  defp do_transform(<<"ℜ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "R">>)
  defp do_transform(<<"ℝ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "R">>)
  defp do_transform(<<"℞", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Rx">>)
  defp do_transform(<<"℡", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "TEL">>)
  defp do_transform(<<"ℤ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Z">>)
  defp do_transform(<<"ℨ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Z">>)
  defp do_transform(<<"ℬ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "B">>)
  defp do_transform(<<"ℭ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "C">>)
  defp do_transform(<<"ℯ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "e">>)
  defp do_transform(<<"ℰ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "E">>)
  defp do_transform(<<"ℱ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "F">>)
  defp do_transform(<<"ℳ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "M">>)
  defp do_transform(<<"ℴ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "o">>)
  defp do_transform(<<"ℹ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "i">>)
  defp do_transform(<<"℻", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "FAX">>)
  defp do_transform(<<"ⅅ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "D">>)
  defp do_transform(<<"ⅆ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "d">>)
  defp do_transform(<<"ⅇ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "e">>)
  defp do_transform(<<"ⅈ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "i">>)
  defp do_transform(<<"ⅉ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "j">>)
  defp do_transform(<<"㍱", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "hPa">>)
  defp do_transform(<<"㍲", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "da">>)
  defp do_transform(<<"㍳", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "AU">>)
  defp do_transform(<<"㍴", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "bar">>)
  defp do_transform(<<"㍵", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "oV">>)
  defp do_transform(<<"㍶", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "pc">>)
  defp do_transform(<<"㍷", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "dm">>)
  defp do_transform(<<"㍺", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "IU">>)
  defp do_transform(<<"㎀", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "pA">>)
  defp do_transform(<<"㎁", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "nA">>)
  defp do_transform(<<"㎃", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "mA">>)
  defp do_transform(<<"㎄", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "kA">>)
  defp do_transform(<<"㎅", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "KB">>)
  defp do_transform(<<"㎆", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "MB">>)
  defp do_transform(<<"㎇", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "GB">>)
  defp do_transform(<<"㎈", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "cal">>)
  defp do_transform(<<"㎉", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "kcal">>)
  defp do_transform(<<"㎊", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "pF">>)
  defp do_transform(<<"㎋", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "nF">>)
  defp do_transform(<<"㎎", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "mg">>)
  defp do_transform(<<"㎏", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "kg">>)
  defp do_transform(<<"㎐", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Hz">>)
  defp do_transform(<<"㎑", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "kHz">>)
  defp do_transform(<<"㎒", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "MHz">>)
  defp do_transform(<<"㎓", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "GHz">>)
  defp do_transform(<<"㎔", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "THz">>)
  defp do_transform(<<"㎙", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "fm">>)
  defp do_transform(<<"㎚", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "nm">>)
  defp do_transform(<<"㎜", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "mm">>)
  defp do_transform(<<"㎝", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "cm">>)
  defp do_transform(<<"㎞", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "km">>)
  defp do_transform(<<"㎧", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "m/s">>)
  defp do_transform(<<"㎩", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Pa">>)
  defp do_transform(<<"㎪", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "kPa">>)
  defp do_transform(<<"㎫", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "MPa">>)
  defp do_transform(<<"㎬", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "GPa">>)
  defp do_transform(<<"㎭", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "rad">>)
  defp do_transform(<<"㎮", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "rad/s">>)
  defp do_transform(<<"㎰", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ps">>)
  defp do_transform(<<"㎱", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ns">>)
  defp do_transform(<<"㎳", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ms">>)
  defp do_transform(<<"㎴", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "pV">>)
  defp do_transform(<<"㎵", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "nV">>)
  defp do_transform(<<"㎷", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "mV">>)
  defp do_transform(<<"㎸", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "kV">>)
  defp do_transform(<<"㎹", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "MV">>)
  defp do_transform(<<"㎺", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "pW">>)
  defp do_transform(<<"㎻", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "nW">>)
  defp do_transform(<<"㎽", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "mW">>)
  defp do_transform(<<"㎾", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "kW">>)
  defp do_transform(<<"㎿", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "MW">>)
  defp do_transform(<<"㏂", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "a.m.">>)
  defp do_transform(<<"㏃", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Bq">>)
  defp do_transform(<<"㏄", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "cc">>)
  defp do_transform(<<"㏅", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "cd">>)
  defp do_transform(<<"㏆", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "C/kg">>)
  defp do_transform(<<"㏇", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Co.">>)
  defp do_transform(<<"㏈", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "dB">>)
  defp do_transform(<<"㏉", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Gy">>)
  defp do_transform(<<"㏊", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ha">>)
  defp do_transform(<<"㏋", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "HP">>)
  defp do_transform(<<"㏌", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "in">>)
  defp do_transform(<<"㏍", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "KK">>)
  defp do_transform(<<"㏎", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "KM">>)
  defp do_transform(<<"㏏", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "kt">>)
  defp do_transform(<<"㏐", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "lm">>)
  defp do_transform(<<"㏑", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ln">>)
  defp do_transform(<<"㏒", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "log">>)
  defp do_transform(<<"㏓", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "lx">>)
  defp do_transform(<<"㏔", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "mb">>)
  defp do_transform(<<"㏕", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "mil">>)
  defp do_transform(<<"㏖", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "mol">>)
  defp do_transform(<<"㏗", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "pH">>)
  defp do_transform(<<"㏘", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "p.m.">>)
  defp do_transform(<<"㏙", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "PPM">>)
  defp do_transform(<<"㏚", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "PR">>)
  defp do_transform(<<"㏛", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "sr">>)
  defp do_transform(<<"㏜", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Sv">>)
  defp do_transform(<<"㏝", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Wb">>)
  defp do_transform(<<"㏞", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "V/m">>)
  defp do_transform(<<"㏟", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "A/m">>)
  defp do_transform(<<"⒜", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(a)">>)
  defp do_transform(<<"⒝", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(b)">>)
  defp do_transform(<<"⒞", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(c)">>)
  defp do_transform(<<"⒟", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(d)">>)
  defp do_transform(<<"⒠", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(e)">>)
  defp do_transform(<<"⒡", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(f)">>)
  defp do_transform(<<"⒢", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(g)">>)
  defp do_transform(<<"⒣", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(h)">>)
  defp do_transform(<<"⒤", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(i)">>)
  defp do_transform(<<"⒥", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(j)">>)
  defp do_transform(<<"⒦", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(k)">>)
  defp do_transform(<<"⒧", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(l)">>)
  defp do_transform(<<"⒨", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(m)">>)
  defp do_transform(<<"⒩", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(n)">>)
  defp do_transform(<<"⒪", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(o)">>)
  defp do_transform(<<"⒫", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(p)">>)
  defp do_transform(<<"⒬", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(q)">>)
  defp do_transform(<<"⒭", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(r)">>)
  defp do_transform(<<"⒮", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(s)">>)
  defp do_transform(<<"⒯", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(t)">>)
  defp do_transform(<<"⒰", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(u)">>)
  defp do_transform(<<"⒱", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(v)">>)
  defp do_transform(<<"⒲", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(w)">>)
  defp do_transform(<<"⒳", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(x)">>)
  defp do_transform(<<"⒴", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(y)">>)
  defp do_transform(<<"⒵", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(z)">>)
  defp do_transform(<<"Ⅰ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "I">>)
  defp do_transform(<<"Ⅱ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "II">>)
  defp do_transform(<<"Ⅲ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "III">>)
  defp do_transform(<<"Ⅳ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "IV">>)
  defp do_transform(<<"Ⅴ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "V">>)
  defp do_transform(<<"Ⅵ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "VI">>)
  defp do_transform(<<"Ⅶ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "VII">>)
  defp do_transform(<<"Ⅷ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "VIII">>)
  defp do_transform(<<"Ⅸ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "IX">>)
  defp do_transform(<<"Ⅹ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "X">>)
  defp do_transform(<<"Ⅺ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "XI">>)
  defp do_transform(<<"Ⅻ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "XII">>)
  defp do_transform(<<"Ⅼ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "L">>)
  defp do_transform(<<"Ⅽ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "C">>)
  defp do_transform(<<"Ⅾ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "D">>)
  defp do_transform(<<"Ⅿ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "M">>)
  defp do_transform(<<"ⅰ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "i">>)
  defp do_transform(<<"ⅱ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ii">>)
  defp do_transform(<<"ⅲ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "iii">>)
  defp do_transform(<<"ⅳ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "iv">>)
  defp do_transform(<<"ⅴ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "v">>)
  defp do_transform(<<"ⅵ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "vi">>)
  defp do_transform(<<"ⅶ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "vii">>)
  defp do_transform(<<"ⅷ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "viii">>)
  defp do_transform(<<"ⅸ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ix">>)
  defp do_transform(<<"ⅹ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "x">>)
  defp do_transform(<<"ⅺ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "xi">>)
  defp do_transform(<<"ⅻ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "xii">>)
  defp do_transform(<<"ⅼ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "l">>)
  defp do_transform(<<"ⅽ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "c">>)
  defp do_transform(<<"ⅾ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "d">>)
  defp do_transform(<<"ⅿ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "m">>)
  defp do_transform(<<"⅐", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 1/7">>)
  defp do_transform(<<"⅑", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 1/9">>)
  defp do_transform(<<"⅒", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 1/10">>)
  defp do_transform(<<"⅓", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 1/3">>)
  defp do_transform(<<"⅔", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 2/3">>)
  defp do_transform(<<"⅕", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 1/5">>)
  defp do_transform(<<"⅖", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 2/5">>)
  defp do_transform(<<"⅗", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 3/5">>)
  defp do_transform(<<"⅘", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 4/5">>)
  defp do_transform(<<"⅙", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 1/6">>)
  defp do_transform(<<"⅚", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 5/6">>)
  defp do_transform(<<"⅛", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 1/8">>)
  defp do_transform(<<"⅜", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 3/8">>)
  defp do_transform(<<"⅝", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 5/8">>)
  defp do_transform(<<"⅞", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 7/8">>)
  defp do_transform(<<"⅟", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 1/">>)
  defp do_transform(<<"↉", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 0/3">>)
  defp do_transform(<<"⑴", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(1)">>)
  defp do_transform(<<"⑵", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(2)">>)
  defp do_transform(<<"⑶", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(3)">>)
  defp do_transform(<<"⑷", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(4)">>)
  defp do_transform(<<"⑸", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(5)">>)
  defp do_transform(<<"⑹", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(6)">>)
  defp do_transform(<<"⑺", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(7)">>)
  defp do_transform(<<"⑻", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(8)">>)
  defp do_transform(<<"⑼", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(9)">>)
  defp do_transform(<<"⑽", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(10)">>)
  defp do_transform(<<"⑾", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(11)">>)
  defp do_transform(<<"⑿", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(12)">>)
  defp do_transform(<<"⒀", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(13)">>)
  defp do_transform(<<"⒁", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(14)">>)
  defp do_transform(<<"⒂", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(15)">>)
  defp do_transform(<<"⒃", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(16)">>)
  defp do_transform(<<"⒄", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(17)">>)
  defp do_transform(<<"⒅", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(18)">>)
  defp do_transform(<<"⒆", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(19)">>)
  defp do_transform(<<"⒇", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(20)">>)
  defp do_transform(<<"⒈", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "1.">>)
  defp do_transform(<<"⒉", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "2.">>)
  defp do_transform(<<"⒊", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "3.">>)
  defp do_transform(<<"⒋", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "4.">>)
  defp do_transform(<<"⒌", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "5.">>)
  defp do_transform(<<"⒍", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "6.">>)
  defp do_transform(<<"⒎", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "7.">>)
  defp do_transform(<<"⒏", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "8.">>)
  defp do_transform(<<"⒐", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "9.">>)
  defp do_transform(<<"⒑", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "10.">>)
  defp do_transform(<<"⒒", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "11.">>)
  defp do_transform(<<"⒓", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "12.">>)
  defp do_transform(<<"⒔", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "13.">>)
  defp do_transform(<<"⒕", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "14.">>)
  defp do_transform(<<"⒖", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "15.">>)
  defp do_transform(<<"⒗", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "16.">>)
  defp do_transform(<<"⒘", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "17.">>)
  defp do_transform(<<"⒙", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "18.">>)
  defp do_transform(<<"⒚", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "19.">>)
  defp do_transform(<<"⒛", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "20.">>)
  defp do_transform(<<"〇", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "0">>)
  defp do_transform(<<"０", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "0">>)
  defp do_transform(<<"１", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "1">>)
  defp do_transform(<<"２", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "2">>)
  defp do_transform(<<"３", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "3">>)
  defp do_transform(<<"４", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "4">>)
  defp do_transform(<<"５", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "5">>)
  defp do_transform(<<"６", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "6">>)
  defp do_transform(<<"７", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "7">>)
  defp do_transform(<<"８", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "8">>)
  defp do_transform(<<"９", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "9">>)
  defp do_transform(<<"\u2002", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " ">>)
  defp do_transform(<<"\u2003", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " ">>)
  defp do_transform(<<"\u2004", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " ">>)
  defp do_transform(<<"\u2005", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " ">>)
  defp do_transform(<<"\u2006", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " ">>)
  defp do_transform(<<"\u2007", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " ">>)
  defp do_transform(<<"\u2008", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " ">>)
  defp do_transform(<<"\u2009", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " ">>)
  defp do_transform(<<"\u200A", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " ">>)
  defp do_transform(<<"\u205F", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " ">>)
  defp do_transform(<<"　", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " ">>)
  defp do_transform(<<"‘", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "'">>)
  defp do_transform(<<"’", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "'">>)
  defp do_transform(<<"‚", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ",">>)
  defp do_transform(<<"‛", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "'">>)
  defp do_transform(<<"“", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "\"">>)
  defp do_transform(<<"”", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "\"">>)
  defp do_transform(<<"„", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ",,">>)
  defp do_transform(<<"‟", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "\"">>)
  defp do_transform(<<"′", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "'">>)
  defp do_transform(<<"″", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "\"">>)
  defp do_transform(<<"〝", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "\"">>)
  defp do_transform(<<"〞", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "\"">>)
  defp do_transform(<<"＂", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "\"">>)
  defp do_transform(<<"＇", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "'">>)
  defp do_transform(<<"‹", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "<">>)
  defp do_transform(<<"›", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ">">>)
  defp do_transform(<<"‐", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "-">>)
  defp do_transform(<<"‑", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "-">>)
  defp do_transform(<<"‒", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "-">>)
  defp do_transform(<<"–", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "-">>)
  defp do_transform(<<"—", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "-">>)
  defp do_transform(<<"―", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "-">>)
  defp do_transform(<<"︱", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "-">>)
  defp do_transform(<<"︲", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "-">>)
  defp do_transform(<<"﹘", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "-">>)
  defp do_transform(<<"﹣", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "-">>)
  defp do_transform(<<"－", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "-">>)
  defp do_transform(<<"‖", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "||">>)
  defp do_transform(<<"․", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ".">>)
  defp do_transform(<<"‥", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "..">>)
  defp do_transform(<<"…", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "...">>)
  defp do_transform(<<"‼", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "!!">>)
  defp do_transform(<<"⁄", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "/">>)
  defp do_transform(<<"⁅", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "[">>)
  defp do_transform(<<"⁆", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "]">>)
  defp do_transform(<<"⁇", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "??">>)
  defp do_transform(<<"⁈", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "?!">>)
  defp do_transform(<<"⁉", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "!?">>)
  defp do_transform(<<"⁎", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "*">>)
  defp do_transform(<<"←", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "<-">>)
  defp do_transform(<<"→", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "->">>)
  defp do_transform(<<"↔", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "<->">>)
  defp do_transform(<<"￩", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "<-">>)
  defp do_transform(<<"￫", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "->">>)
  defp do_transform(<<"、", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ",">>)
  defp do_transform(<<"。", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ".">>)
  defp do_transform(<<"〈", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "<">>)
  defp do_transform(<<"〉", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ">">>)
  defp do_transform(<<"《", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "<<">>)
  defp do_transform(<<"》", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ">>">>)
  defp do_transform(<<"〔", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "[">>)
  defp do_transform(<<"〕", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "]">>)
  defp do_transform(<<"〘", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "[">>)
  defp do_transform(<<"〙", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "]">>)
  defp do_transform(<<"〚", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "[">>)
  defp do_transform(<<"〛", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "]">>)
  defp do_transform(<<"︐", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ",">>)
  defp do_transform(<<"︑", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ",">>)
  defp do_transform(<<"︒", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ".">>)
  defp do_transform(<<"︓", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ":">>)
  defp do_transform(<<"︔", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ";">>)
  defp do_transform(<<"︕", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "!">>)
  defp do_transform(<<"︖", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "?">>)
  defp do_transform(<<"︙", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "...">>)
  defp do_transform(<<"︰", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "..">>)
  defp do_transform(<<"︵", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(">>)
  defp do_transform(<<"︶", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ")">>)
  defp do_transform(<<"︷", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "{">>)
  defp do_transform(<<"︸", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "}">>)
  defp do_transform(<<"︹", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "[">>)
  defp do_transform(<<"︺", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "]">>)
  defp do_transform(<<"︽", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "<<">>)
  defp do_transform(<<"︾", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ">>">>)
  defp do_transform(<<"︿", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "<">>)
  defp do_transform(<<"﹀", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ">">>)
  defp do_transform(<<"﹇", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "[">>)
  defp do_transform(<<"﹈", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "]">>)
  defp do_transform(<<"﹐", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ",">>)
  defp do_transform(<<"﹑", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ",">>)
  defp do_transform(<<"﹒", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ".">>)
  defp do_transform(<<"﹔", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ";">>)
  defp do_transform(<<"﹕", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ":">>)
  defp do_transform(<<"﹖", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "?">>)
  defp do_transform(<<"﹗", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "!">>)
  defp do_transform(<<"﹙", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(">>)
  defp do_transform(<<"﹚", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ")">>)
  defp do_transform(<<"﹛", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "{">>)
  defp do_transform(<<"﹜", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "}">>)
  defp do_transform(<<"﹝", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "[">>)
  defp do_transform(<<"﹞", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "]">>)
  defp do_transform(<<"﹟", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "#">>)
  defp do_transform(<<"﹠", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "&">>)
  defp do_transform(<<"﹡", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "*">>)
  defp do_transform(<<"﹢", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "+">>)
  defp do_transform(<<"﹤", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "<">>)
  defp do_transform(<<"﹥", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ">">>)
  defp do_transform(<<"﹦", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "=">>)
  defp do_transform(<<"﹨", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "">>)
  defp do_transform(<<"﹩", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "$">>)
  defp do_transform(<<"﹪", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "%">>)
  defp do_transform(<<"﹫", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "@">>)
  defp do_transform(<<"！", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "!">>)
  defp do_transform(<<"＃", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "#">>)
  defp do_transform(<<"＄", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "$">>)
  defp do_transform(<<"％", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "%">>)
  defp do_transform(<<"＆", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "&">>)
  defp do_transform(<<"（", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(">>)
  defp do_transform(<<"）", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ")">>)
  defp do_transform(<<"＊", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "*">>)
  defp do_transform(<<"＋", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "+">>)
  defp do_transform(<<"，", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ",">>)
  defp do_transform(<<"．", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ".">>)
  defp do_transform(<<"／", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "/">>)
  defp do_transform(<<"：", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ":">>)
  defp do_transform(<<"；", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ";">>)
  defp do_transform(<<"＜", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "<">>)
  defp do_transform(<<"＝", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "=">>)
  defp do_transform(<<"＞", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ">">>)
  defp do_transform(<<"？", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "?">>)
  defp do_transform(<<"＠", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "@">>)
  defp do_transform(<<"［", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "[">>)
  defp do_transform(<<"＼", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "">>)
  defp do_transform(<<"］", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "]">>)
  defp do_transform(<<"＾", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "^">>)
  defp do_transform(<<"＿", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "_">>)
  defp do_transform(<<"｀", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "`">>)
  defp do_transform(<<"｛", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "{">>)
  defp do_transform(<<"｜", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "|">>)
  defp do_transform(<<"｝", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "}">>)
  defp do_transform(<<"～", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "~">>)
  defp do_transform(<<"｟", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "((">>)
  defp do_transform(<<"｠", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "))">>)
  defp do_transform(<<"｡", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ".">>)
  defp do_transform(<<"､", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ",">>)
  defp do_transform(<<"−", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "-">>)
  defp do_transform(<<"∕", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "/">>)
  defp do_transform(<<"∖", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "">>)
  defp do_transform(<<"∣", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "|">>)
  defp do_transform(<<"∥", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "||">>)
  defp do_transform(<<"≪", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "<<">>)
  defp do_transform(<<"≫", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ">>">>)
  defp do_transform(<<"⦅", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "((">>)
  defp do_transform(<<"⦆", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "))">>)
  defp do_transform(<<"⩴", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "::=">>)
  defp do_transform(<<"⩵", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "==">>)
  defp do_transform(<<"⩶", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "===">>)
  defp do_transform(<<"Æ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "AE">>)
  defp do_transform(<<"Ð", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "D">>)
  defp do_transform(<<"Ø", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "O">>)
  defp do_transform(<<"Þ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "TH">>)
  defp do_transform(<<"ß", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ss">>)
  defp do_transform(<<"æ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ae">>)
  defp do_transform(<<"ð", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "d">>)
  defp do_transform(<<"ø", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "o">>)
  defp do_transform(<<"þ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "th">>)
  defp do_transform(<<"Đ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "D">>)
  defp do_transform(<<"đ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "d">>)
  defp do_transform(<<"Ħ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "H">>)
  defp do_transform(<<"ħ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "h">>)
  defp do_transform(<<"ı", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "i">>)
  defp do_transform(<<"Ĳ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "IJ">>)
  defp do_transform(<<"ĳ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ij">>)
  defp do_transform(<<"ĸ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "q">>)
  defp do_transform(<<"Ŀ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "L">>)
  defp do_transform(<<"ŀ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "l">>)
  defp do_transform(<<"Ł", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "L">>)
  defp do_transform(<<"ł", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "l">>)
  defp do_transform(<<"ŉ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "'n">>)
  defp do_transform(<<"Ŋ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "N">>)
  defp do_transform(<<"ŋ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "n">>)
  defp do_transform(<<"Œ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "OE">>)
  defp do_transform(<<"œ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "oe">>)
  defp do_transform(<<"Ŧ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "T">>)
  defp do_transform(<<"ŧ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "t">>)
  defp do_transform(<<"ſ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "s">>)
  defp do_transform(<<"ƀ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "b">>)
  defp do_transform(<<"Ɓ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "B">>)
  defp do_transform(<<"Ƃ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "B">>)
  defp do_transform(<<"ƃ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "b">>)
  defp do_transform(<<"Ƈ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "C">>)
  defp do_transform(<<"ƈ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "c">>)
  defp do_transform(<<"Ɖ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "D">>)
  defp do_transform(<<"Ɗ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "D">>)
  defp do_transform(<<"Ƌ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "D">>)
  defp do_transform(<<"ƌ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "d">>)
  defp do_transform(<<"Ɛ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "E">>)
  defp do_transform(<<"Ƒ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "F">>)
  defp do_transform(<<"ƒ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "f">>)
  defp do_transform(<<"Ɠ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "G">>)
  defp do_transform(<<"ƕ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "hv">>)
  defp do_transform(<<"Ɩ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "I">>)
  defp do_transform(<<"Ɨ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "I">>)
  defp do_transform(<<"Ƙ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "K">>)
  defp do_transform(<<"ƙ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "k">>)
  defp do_transform(<<"ƚ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "l">>)
  defp do_transform(<<"Ɲ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "N">>)
  defp do_transform(<<"ƞ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "n">>)
  defp do_transform(<<"Ƣ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "OI">>)
  defp do_transform(<<"ƣ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "oi">>)
  defp do_transform(<<"Ƥ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "P">>)
  defp do_transform(<<"ƥ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "p">>)
  defp do_transform(<<"ƫ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "t">>)
  defp do_transform(<<"Ƭ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "T">>)
  defp do_transform(<<"ƭ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "t">>)
  defp do_transform(<<"Ʈ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "T">>)
  defp do_transform(<<"Ʋ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "V">>)
  defp do_transform(<<"Ƴ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Y">>)
  defp do_transform(<<"ƴ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "y">>)
  defp do_transform(<<"Ƶ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Z">>)
  defp do_transform(<<"ƶ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "z">>)
  defp do_transform(<<"Ǆ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "DZ">>)
  defp do_transform(<<"ǅ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Dz">>)
  defp do_transform(<<"ǆ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "dz">>)
  defp do_transform(<<"Ǉ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "LJ">>)
  defp do_transform(<<"ǈ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Lj">>)
  defp do_transform(<<"ǉ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "lj">>)
  defp do_transform(<<"Ǌ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "NJ">>)
  defp do_transform(<<"ǋ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Nj">>)
  defp do_transform(<<"ǌ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "nj">>)
  defp do_transform(<<"Ǥ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "G">>)
  defp do_transform(<<"ǥ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "g">>)
  defp do_transform(<<"Ǳ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "DZ">>)
  defp do_transform(<<"ǲ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Dz">>)
  defp do_transform(<<"ǳ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "dz">>)
  defp do_transform(<<"ȡ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "d">>)
  defp do_transform(<<"Ȥ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Z">>)
  defp do_transform(<<"ȥ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "z">>)
  defp do_transform(<<"ȴ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "l">>)
  defp do_transform(<<"ȵ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "n">>)
  defp do_transform(<<"ȶ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "t">>)
  defp do_transform(<<"ȷ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "j">>)
  defp do_transform(<<"ȸ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "db">>)
  defp do_transform(<<"ȹ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "qp">>)
  defp do_transform(<<"Ⱥ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "A">>)
  defp do_transform(<<"Ȼ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "C">>)
  defp do_transform(<<"ȼ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "c">>)
  defp do_transform(<<"Ƚ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "L">>)
  defp do_transform(<<"Ⱦ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "T">>)
  defp do_transform(<<"ȿ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "s">>)
  defp do_transform(<<"ɀ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "z">>)
  defp do_transform(<<"Ƀ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "B">>)
  defp do_transform(<<"Ʉ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "U">>)
  defp do_transform(<<"Ɇ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "E">>)
  defp do_transform(<<"ɇ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "e">>)
  defp do_transform(<<"Ɉ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "J">>)
  defp do_transform(<<"ɉ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "j">>)
  defp do_transform(<<"Ɍ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "R">>)
  defp do_transform(<<"ɍ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "r">>)
  defp do_transform(<<"Ɏ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Y">>)
  defp do_transform(<<"ɏ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "y">>)
  defp do_transform(<<"ɓ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "b">>)
  defp do_transform(<<"ɕ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "c">>)
  defp do_transform(<<"ɖ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "d">>)
  defp do_transform(<<"ɗ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "d">>)
  defp do_transform(<<"ɛ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "e">>)
  defp do_transform(<<"ɟ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "j">>)
  defp do_transform(<<"ɠ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "g">>)
  defp do_transform(<<"ɡ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "g">>)
  defp do_transform(<<"ɢ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "G">>)
  defp do_transform(<<"ɦ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "h">>)
  defp do_transform(<<"ɧ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "h">>)
  defp do_transform(<<"ɨ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "i">>)
  defp do_transform(<<"ɪ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "I">>)
  defp do_transform(<<"ɫ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "l">>)
  defp do_transform(<<"ɬ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "l">>)
  defp do_transform(<<"ɭ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "l">>)
  defp do_transform(<<"ɱ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "m">>)
  defp do_transform(<<"ɲ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "n">>)
  defp do_transform(<<"ɳ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "n">>)
  defp do_transform(<<"ɴ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "N">>)
  defp do_transform(<<"ɶ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "OE">>)
  defp do_transform(<<"ɼ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "r">>)
  defp do_transform(<<"ɽ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "r">>)
  defp do_transform(<<"ɾ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "r">>)
  defp do_transform(<<"ʀ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "R">>)
  defp do_transform(<<"ʂ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "s">>)
  defp do_transform(<<"ʈ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "t">>)
  defp do_transform(<<"ʉ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "u">>)
  defp do_transform(<<"ʋ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "v">>)
  defp do_transform(<<"ʏ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "Y">>)
  defp do_transform(<<"ʐ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "z">>)
  defp do_transform(<<"ʑ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "z">>)
  defp do_transform(<<"ʙ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "B">>)
  defp do_transform(<<"ʛ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "G">>)
  defp do_transform(<<"ʜ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "H">>)
  defp do_transform(<<"ʝ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "j">>)
  defp do_transform(<<"ʟ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "L">>)
  defp do_transform(<<"ʠ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "q">>)
  defp do_transform(<<"ʣ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "dz">>)
  defp do_transform(<<"ʥ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "dz">>)
  defp do_transform(<<"ʦ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ts">>)
  defp do_transform(<<"ʪ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "ls">>)
  defp do_transform(<<"ʫ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "lz">>)
  defp do_transform(<<"©", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(C)">>)
  defp do_transform(<<"®", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "(R)">>)
  defp do_transform(<<"¼", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 1/4">>)
  defp do_transform(<<"½", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 1/2">>)
  defp do_transform(<<"¾", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " 3/4">>)
  defp do_transform(<<"\u00A0", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, " ">>)
  defp do_transform(<<"ʹ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "'">>)
  defp do_transform(<<"ʺ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "\"">>)
  defp do_transform(<<"ʻ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "'">>)
  defp do_transform(<<"ʼ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "'">>)
  defp do_transform(<<"ʽ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "'">>)
  defp do_transform(<<"ˈ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "'">>)
  defp do_transform(<<"ˋ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "`">>)
  defp do_transform(<<"«", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "<<">>)
  defp do_transform(<<"»", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ">>">>)
  defp do_transform(<<"­", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "-">>)
  defp do_transform(<<"¡", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "!">>)
  defp do_transform(<<"¿", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "?">>)
  defp do_transform(<<"˂", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "<">>)
  defp do_transform(<<"˃", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ">">>)
  defp do_transform(<<"˄", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "^">>)
  defp do_transform(<<"ˆ", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "^">>)
  defp do_transform(<<"ː", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, ":">>)
  defp do_transform(<<"˜", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "~">>)
  defp do_transform(<<"±", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "+/-">>)
  defp do_transform(<<"×", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "*">>)
  defp do_transform(<<"÷", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "/">>)
  defp do_transform(<<"˖", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "+">>)
  defp do_transform(<<"˗", rest::binary>>, acc), do: do_transform(rest, <<acc::binary, "-">>)

  # Strip combining marks (Unicode General Category Mn = Nonspacing Mark).
  # After NFD, combining diacritical marks follow their base character.
  # We skip them to produce ASCII output.
  defp do_transform(<<cp::utf8, rest::binary>>, acc) when cp >= 0x300 and cp <= 0x36F,
    do: do_transform(rest, acc)

  defp do_transform(<<cp::utf8, rest::binary>>, acc) when cp >= 0x1AB0 and cp <= 0x1AFF,
    do: do_transform(rest, acc)

  defp do_transform(<<cp::utf8, rest::binary>>, acc) when cp >= 0x1DC0 and cp <= 0x1DFF,
    do: do_transform(rest, acc)

  defp do_transform(<<cp::utf8, rest::binary>>, acc) when cp >= 0x20D0 and cp <= 0x20FF,
    do: do_transform(rest, acc)

  defp do_transform(<<cp::utf8, rest::binary>>, acc) when cp >= 0xFE20 and cp <= 0xFE2F,
    do: do_transform(rest, acc)

  # Passthrough for unmatched codepoints
  defp do_transform(<<cp::utf8, rest::binary>>, acc) do
    do_transform(rest, <<acc::binary, cp::utf8>>)
  end

  defp do_transform(<<>>, acc), do: acc
end
